// <auto-generated />
using System;
using KhoraControl.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KhoraControl.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("KhoraControl.Domain.Models.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("user_account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("KhoraControl.Domain.Models.Entities.UserAccountPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_account_id");

                    b.Property<string>("UserPolicy")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_policy");

                    b.HasKey("Id");

                    b.ToTable("user_account_policy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEnabled = true,
                            UserAccountId = 1,
                            UserPolicy = "VIEW_PRODUCT"
                        },
                        new
                        {
                            Id = 2,
                            IsEnabled = true,
                            UserAccountId = 1,
                            UserPolicy = "UPDATE_PRODUCT"
                        },
                        new
                        {
                            Id = 3,
                            IsEnabled = true,
                            UserAccountId = 1,
                            UserPolicy = "DELETE_PRODUCT"
                        },
                        new
                        {
                            Id = 4,
                            IsEnabled = true,
                            UserAccountId = 1,
                            UserPolicy = "CREATE_PRODUCT"
                        });
                });

            modelBuilder.Entity("KhoraControl.Domain.Models.Fornecedor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("CEP")
                        .HasColumnType("TEXT");

                    b.Property<string>("CNPJ")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodRegimeTributario")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoPais")
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("KhoraControl.Domain.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRONID_PRO");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("TEXT")
                        .HasColumnName("PROCCODINT");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("PRODDATALT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("PRODDATCAD");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("TEXT")
                        .HasColumnName("PRODDATVAL");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROCDESCR");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROCFOR");

                    b.Property<string>("NumeroNotaFiscal")
                        .HasColumnType("TEXT")
                        .HasColumnName("PROCNNUMNF");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRONQUANT");

                    b.Property<string>("ReferenciaFornecedor")
                        .HasColumnType("TEXT")
                        .HasColumnName("PROCREF");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("PROCSTAT");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("TEXT")
                        .HasColumnName("PROCUSRALT");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("PROCUSRCAD");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
